def transcribeDNA(seq):
    seq = seq.replace("T","U")
    return seq
  transcribeDNA("GGGCCTTTTTGCGAGTTGCTTCTATCGCCGGACAACATTACGACAGGTGCCACTATTTTTGATAAGAAATCCCGACCACTTTCCGGGTTGCTCTACCGGTGGTACCCGTACACATACAGTACCTCAGACGTCAGGTGTGTGCCAATA")
